name:                packed-data
version:             0.1.0.3
github:              "Arthi-chaud/packed-haskell"
license:             BSD-3-Clause
author:              "Arthi-chaud"
maintainer:          "aj530@kent.ac.uk"
copyright:           "2025 Arthi-chaud"
category:            "Data" 

extra-source-files:
- README.md

description:        Build, traverse and deserialise packed data in Haskell 

dependencies:
- base >= 4.7 && < 5

tested-with:
- GHC ==9.2.8
- GHC ==9.4.8
- GHC ==9.6.6
- GHC ==9.8.4
- GHC ==9.10.1
- GHC ==9.12.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- DataKinds
- TypeOperators
- KindSignatures
- GADTs
- LambdaCase
- TemplateHaskell
- TemplateHaskellQuotes
- TupleSections
- QualifiedDo

library:
  source-dirs: src
  dependencies:
  - bytestring >=0.11.0.0 && <0.13
  - extra >= 1.0 && <2.0
  - template-haskell >=2.18.0.0 && <=2.24.0.0
  - bytestring-strict-builder >= 0.4.5 && <0.5
  - deepseq >=1.4.6.1 && <1.6
  - mtl >=2.2.2 && <2.4
  exposed-modules:
  - Data.Packed
  - Data.Packed.Reader
  - Data.Packed.Needs
  - Data.Packed.Instances
  - Data.Packed.TH
  - Data.Packed.TH.Utils
  - Data.Packed.Skippable
  - Data.Packed.FieldSize

executables:
  examples:
    main:                Main.hs
    source-dirs:         examples 
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-unused-top-binds
    dependencies:
    - packed-data

tests:
  packed-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-unused-top-binds
    - -Wno-orphans
    - -Wno-redundant-constraints
    dependencies:
    - packed-data
    - bytestring-strict-builder >= 0.4.5 && <0.5
    - hspec
    - bytestring

benchmarks:
  tree-bench:
    source-dirs:      benchmark/tree
    main:             Main.hs
    include-dirs: 
    - benchmark 
    c-sources: benchmark/tree/benchmark.c
    cc-options: -O2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-T
    - -O2
    - -Wno-unused-top-binds
    - -Wno-orphans
    - -Wno-redundant-constraints
    dependencies:
    - packed-data
    - criterion
    - bytestring
    - deepseq
    - optparse-applicative
    - cassava
    - vector
    - split
    - listsafe
    - filepath
    - directory
    - aeson
    - mtl
  bigjson-bench:
    source-dirs:      benchmark/bigjson
    main:             Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-T
    - -O2
    - -Wno-unused-top-binds
    - -Wno-orphans
    - -Wno-redundant-constraints
    dependencies:
    - packed-data
    - criterion
    - bytestring
    - aeson
    - directory
    - optparse-applicative
  ast-bench:
    source-dirs:      benchmark/ast
    main:             Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-T
    - -O2
    - -Wno-unused-top-binds
    - -Wno-orphans
    - -Wno-redundant-constraints
    dependencies:
    - packed-data
    - criterion
    - optparse-applicative

  # Note: Not a benchmark suite, compiles results for paper
  report:
    source-dirs:      benchmark/report
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-T
    - -O2
    - -Wno-unused-top-binds
    - -Wno-orphans
    - -Wno-redundant-constraints
    dependencies:
    - process
    - bytestring
    - directory
    - scientific
    - cassava
