name: "Packed Haskell"
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash
    working-directory: .

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write
  # allow posting comments to pull request
  pull-requests: write

jobs:
  Changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packed: ${{ steps.filter.outputs.packed }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            packed:
              - '**'
  Build:
    needs: changes
    if: ${{ needs.changes.outputs.packed == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        ghc-version: [
          # 9.0.2,
          # 9.2.8,
          # 9.4.8, 
          # 9.6.6,
          # 9.8.4,
          9.10.1,
          9.12.1
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Setup GHC
        uses: ./.github/actions/cache-packed
        with:
          ghc-version: ${{ matrix.ghc-version }}
      - name: Build 
        run: |
          stack --compiler ghc-${{ matrix.ghc-version }} build packed-data:exe:examples \
            packed-data:test:packed-test \
            --no-run-tests
  Format:
    if: ${{ needs.changes.outputs.packed == 'true' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup GHC
        uses: ./.github/actions/cache-packed
      - uses: haskell-actions/run-fourmolu@v9
        with:
          version: "0.18.0.0"
          pattern: |
            **/*.hs
            !.stack-work/
          follow-symbolic-links: false
  Lint:
    if: ${{ needs.changes.outputs.packed == 'true' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup GHC
        uses: ./.github/actions/cache-packed
      - name: 'Set up HLint'
        uses: rwe/actions-hlint-setup@v1
        with:
          version: '3.10'
      - name: 'Run HLint'
        uses: rwe/actions-hlint-run@v2
        with:
          path: '["src/", "test/"]'
          fail-on: warning
  Tests:
    runs-on: ubuntu-latest
    needs: [ Build ]
    strategy:
      fail-fast: false
      matrix:
        ghc-version: [
          # 9.0.2,
          # 9.2.8,
          # 9.4.8, 
          # 9.6.6,
          # 9.8.4,
          9.10.1,
          9.12.1
        ]
    if: ${{ needs.changes.outputs.packed == 'true' && always() }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup GHC
        uses: ./.github/actions/cache-packed
        with:
          ghc-version: ${{ matrix.ghc-version }}
      - name: Run unit tests
        run: stack test --compiler ghc-${{ matrix.ghc-version }}
  Benchmark:
    if: ${{ needs.changes.outputs.packed == 'true' && always() }}
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup GHC
        uses: ./.github/actions/cache-packed
      - name: 'Run Benchmark'
        run: stack build packed-data:bench:tree-bench --ba '--csv benchmark-report.csv -L 1'
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customSmallerIsBetter'
          summary-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          output-file-path: benchmark-report.json
          fail-on-alert: true
          benchmark-data-dir-path: "docs"
